apiVersion: v1
kind: Service
metadata:
  name: my-website-svc
  namespace: web
  labels:
    app: myweb
    #  annotations:
    #cloud.google.com/neg: '{"ingress": true}'
    #cloud.google.com/backend-config: '{"default":"web-bc"}'
spec:
  type: NodePort
  selector:
    app: myweb
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
